org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=1.21.11
forge_version=61.1.0
forge_loader_range=[61,)

mod_id=luckybreak
mod_name=Lucky Break
mod_version=3.0.0
mod_authors=af-an
mod_description=Find and break the Lucky Block and it just might be your Lucky Break.

maven_group=com.luckybreak
archives_base_name=luckybreak